apiVersion: batch/v1
kind: CronJob
metadata:
  name: ridership-processor
  namespace: data-jobs
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ridership-processor
              image: ghcr.io/ankoure/ridership-processor:latest
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "2Gi"
                  cpu: "1"
              envFrom:
                - secretRef:
                    name: aws-credentials
